title: SSRS Reports Migration Wizard
description: Manage SSRS reports from one server to another.
theme:
  name: material
  features:
    - navigation.tabs # Adds horizontal tabs for cleaner look
    - navigation.sections # Groups sidebar items better
    - navigation.expand # Keeps sidebar expanded for visibility
    - content.code.copy # Adds a copy button to code blocks

url: https://ssrsmigrationwizard.azureops.org

aux_links:
  "Activate Now":
    - "https://azureops.org/product/ssrs-reports-migration-wizard/"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true
hide_icon: false # set to true to hide the external link icon - defaults to false

favicon_ico: "/assets/images/favicon.ico"

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red
